### ISSUE TITLE
Error on plugin install

### ISSUE THREAD

**Issue by PerfectedApp** [grrr-amsterdam/simply-static-deploy#22]
When trying to add the plugin I get the following hard crash:

Uncaught TypeError: Argument 3 passed to Garp\\Functional\\reduce() must be an instance of Garp\\Functional\\iterable, array given, called in /var/www/wordpress/main/wp-content/plugins/simply-static-deploy/includes/DependencyList.php on line 25 and defined in /var/www/wordpress/main/wp-content/plugins/simply-static-deploy/vendor/grrr-amsterdam/garp-functional/functions/reduce.php:20\nStack trace:\n#0 /var/www/wordpress/main/wp-content/plugins/simply-static-deploy/includes/DependencyList.php(25): Garp\\Functional\\reduce(Object(Closure), true, Array)\n#1 /var/www/wordpress/main/wp-content/plugins/simply-static-deploy/includes/SimplyStaticDeploy.php(27): Grrr\\SimplyStaticDeploy\\DependencyList->are_met()\n#2 /var/www/wordpress/main/wp-includes/class-wp-hook.php(288): Grrr\\SimplyStaticDeploy\\SimplyStaticDeploy->plugins_loaded('')\n#3 /var/www/wordpress/main/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)\n#4 /var/www/wordpress/main/wp-includes/plugin.php(478): WP_Hook->do_action(Array)\n#5 /var/www/wor in /var/www/wordpress/main/wp-content/plugins/simply-static-deploy/vendor/grrr-amsterdam/garp-functional/functions/reduce.php on line 20

**Comment by martijngastkemper** [comment]
Which PHP version do you use? Your version doesn't seem to have support for `iterable`.
